development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: HEALTHHACKDUB_DATABASE_DEVELOPMENT
  pool: 5
  username: postgres
  password: password99
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: HEALTHHACKDUB_DATABASE_TEST
  pool: 5
  username: postgres
  password: password99
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: HEALTHHACKDUB_DATABASE_PRODUCTION
  pool: 5
  username: postgres
  password:  password99